openapi: 3.0.0
info:
  title: Ray API
  description: API built to interact with the data layer needed for Ray's services
  version: 0.0.1

servers:
  - url: http://192.168.0.12:8000
    description: Server when running on dell inspiron

paths:
  # ---- ECHO ----
  /echo/hello:
    get:
      summary: 'Check if system is online'
      description: 'Idempotent request meant to check if system is online'
      responses:
        '200':
          description: 'Successful call to system'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardResponse'
              example: {
                statusCode: 200,
                type: "string",
                results: ["Hello world 2"]
              }
              
  /echo/time:
    get:
      summary: 'Check the current system time'
      description: 'Request to provide information about time on the system'
      responses:
        '200':
          description: 'System time succeeded'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardResponse'
              example: {
                statusCode: 200,
                type: "DateTime",
                results: ["12:34:1234 MST"]
              }
      
  # ---- CLOTHING ----
  /clothing/item:

  /clothing/items:
    get:
      parameters:
        
  /clothing/outfit:
    get:
      parameters:

      reponses:
      
  /clothing/outfit/accepted:
    post:
      parameters:

      reponses:

  /clothing/outfit/rejected:
    post:
      parameters:

      reponses:
      


  # ---- FOOD ----
  /food/groceries:

  /food/recipes:

  # ---- TODO ----
  /todo/calendar:

  /todo/reminders:
    get:

components:
  schemas:
    StandardResponse:
      type: object
      properties:
        statusCode:
          type: integer
        results:
          type: array
          items:
            type: object
        type:
          type: string
      required: 
        - statusCode
          results
          type