# Generated by Django 3.0.4 on 2020-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.IntegerField(default=-1),
        ),
    ]
