# Generated by Django 3.0.4 on 2020-04-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_reminder_priority'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reminder',
            table=None,
        ),
    ]
