# Generated by Django 3.0.4 on 2020-04-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grocery',
            table='groceries',
        ),
    ]
