# Generated by Django 3.0.4 on 2020-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200408_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
