# Generated by Django 3.0.4 on 2020-04-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200408_1247'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grocery',
            table=None,
        ),
    ]
